import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { Activity, ArrowUpRight, BrainCircuit, ChevronDown, CircleHelp, FileText, Gauge, GraduationCap, Layers3, Lightbulb, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Users, X } from "lucide-react";

const navItems = [
  ["Overview", Gauge], ["My Twin", BrainCircuit], ["Classes", Users], ["Insights", Lightbulb], ["Content", FileText], ["Settings", Settings],
] as const;

const dna = [["Analogies", "87%"], ["Real-world examples", "91%"], ["Step-by-step reasoning", "78%"], ["Socratic questioning", "64%"], ["Visual explanations", "72%"]];

export default function Workspace() {
  const [active, setActive] = useState("Overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const isTwin = active === "My Twin";
  const showToast = (message: string) => toast(message);
  return <main className="workspace-shell">
    <aside className={`workspace-sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="workspace-brand"><Link href="/"><span className="brand-glyph">P</span><strong>praxis</strong></Link><button className="sidebar-close" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <div className="teacher-profile"><div className="teacher-avatar">SA</div><div><strong>Dr. Sarah Adeyemi</strong><span>Biology · Undergraduate</span></div><ChevronDown size={15} /></div>
      <span className="workspace-label">Workspace</span>
      <nav className="workspace-nav">{navItems.map(([label, Icon]) => <button key={label} className={active === label ? "active" : ""} onClick={() => { setActive(label); setMobileOpen(false); }}><Icon size={16} />{label}{label === "Insights" && <span className="nav-badge">1</span>}</button>)}</nav>
      <div className="sidebar-bottom"><button onClick={() => showToast("Help center coming soon")}><CircleHelp size={16} /> Help center</button><div className="sidebar-version">Praxis demo workspace<br />v0.4.2</div></div>
    </aside>
    <section className="workspace-main"><header className="workspace-topbar"><button className="workspace-menu" onClick={() => setMobileOpen(true)}><Menu size={19} /></button><div className="workspace-search"><Search size={15} /><span>Search your workspace</span><kbd>⌘ K</kbd></div><div className="workspace-actions"><button onClick={() => showToast("No new notifications")} className="notification-button"><span /> <Activity size={17} /></button><button onClick={() => showToast("Invite link copied")} className="invite-button"><Plus size={15} /> Invite</button><div className="small-avatar">SA</div></div></header>
      <div className="workspace-content">{isTwin ? <TwinView showToast={showToast} /> : <OverviewView showToast={showToast} setActive={setActive} />}</div>
    </section>
  </main>;
}

function OverviewView({ showToast, setActive }: { showToast: (message: string) => void; setActive: (active: string) => void }) {
  return <>
    <div className="workspace-heading"><div><span className="micro-label">THURSDAY, OCTOBER 24, 2025</span><h1>Good morning, Sarah.</h1><p>Here's what's happening across your classroom.</p></div><button className="workspace-primary" onClick={() => showToast("Content upload coming soon")}><Plus size={16} /> Add content</button></div>
    <div className="metric-row"><div className="metric-card"><span>Classes</span><strong>3</strong><small><span className="metric-up">↗ 1</span> this semester</small></div><div className="metric-card"><span>Students</span><strong>84</strong><small><span className="metric-up">↗ 6</span> this semester</small></div><div className="metric-card"><span>Average mastery</span><strong>76%</strong><small><span className="metric-up">↗ 4.2%</span> this week</small></div><div className="metric-card metric-card-accent"><span>Teaching DNA match</span><strong>84</strong><small>Across 42 materials</small></div></div>
    <div className="workspace-alert"><div className="alert-icon"><Sparkles size={18} /></div><div className="alert-copy"><span className="alert-label">PRAXIS NOTICED SOMETHING <span>2m ago</span></span><h2>Cellular respiration is becoming a learning bottleneck.</h2><p>41% of students are currently below expected mastery in <strong>Biology 204 · Cell Systems.</strong></p><div className="alert-actions"><button className="workspace-primary" onClick={() => showToast("Insight details opened")}>View insight <ArrowUpRight size={14} /></button><button className="plain-button" onClick={() => showToast("Insight dismissed")}>Dismiss</button></div></div><div className="alert-chart"><div className="chart-label"><span>MASTERY TREND</span><strong>−12%</strong></div><div className="line-chart"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="chart-axis"><span>OCT 01</span><span>OCT 24</span></div></div></div>
    <div className="dashboard-grid"><div className="workspace-panel"><div className="panel-title"><div><span className="micro-label">ACTIVE CLASSES</span><h3>Classroom pulse</h3></div><button onClick={() => setActive("Classes")}><MoreHorizontal size={17} /></button></div><div className="class-list"><div className="class-row"><div className="class-icon bio">BIO</div><div><strong>Biology 204 · Cell Systems</strong><span>32 students · Last active today</span></div><div className="mastery"><strong>68%</strong><span>mastery</span></div></div><div className="class-row"><div className="class-icon org">ORG</div><div><strong>Biology 101 · Foundations</strong><span>28 students · Last active yesterday</span></div><div className="mastery good"><strong>82%</strong><span>mastery</span></div></div><div className="class-row"><div className="class-icon evo">EVO</div><div><strong>Research Seminar</strong><span>24 students · Last active Oct 22</span></div><div className="mastery good"><strong>79%</strong><span>mastery</span></div></div></div></div><div className="workspace-panel quick-panel"><div className="panel-title"><div><span className="micro-label">QUICK ACCESS</span><h3>Keep going</h3></div></div><button onClick={() => setActive("My Twin")}><BrainCircuit size={18} /><span><strong>Review your Praxis Twin</strong><small>3 new teaching patterns</small></span><ArrowUpRight size={14} /></button><button onClick={() => setActive("Content")}><Layers3 size={18} /><span><strong>Continue building a lesson</strong><small>Cellular respiration · 72% complete</small></span><ArrowUpRight size={14} /></button><button onClick={() => setActive("Insights")}><Lightbulb size={18} /><span><strong>See recent insights</strong><small>4 new observations this week</small></span><ArrowUpRight size={14} /></button></div></div>
  </>;
}

function TwinView({ showToast }: { showToast: (message: string) => void }) {
  return <><div className="workspace-heading twin-heading"><div><span className="micro-label">MY TWIN / TEACHING DNA</span><h1>Your Praxis Twin.</h1><p>An AI model shaped by the way you teach.</p></div><button className="workspace-secondary" onClick={() => showToast("Profile export coming soon")}>Export profile <ArrowUpRight size={14} /></button></div><div className="twin-layout"><div className="twin-profile-card"><div className="twin-card-top"><div className="twin-orbit"><BrainCircuit size={27} /></div><div><span className="micro-label">PROFILE MATCH</span><strong>84%</strong></div></div><div className="twin-wave"><span /><span /><span /><span /><span /><span /><span /><span /><span /></div><div className="twin-card-foot"><span>Last analyzed today</span><span>42 materials</span></div></div><div className="twin-dna-panel"><div className="panel-title"><div><span className="micro-label">DETECTED PATTERNS</span><h3>Teaching DNA</h3></div><button onClick={() => showToast("DNA editing is coming soon")}><Settings size={16} /></button></div>{dna.map(([label, value]) => <div className="twin-dna-row" key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="twin-progress"><i style={{ width: value }} /></div></div>)}<div className="twin-note"><Sparkles size={14} /><span>These values reflect patterns detected from your teaching materials.</span></div></div></div><div className="learned-section"><div className="panel-title"><div><span className="micro-label">HOW PRAXIS LEARNED YOUR STYLE</span><h3>What your materials tell us</h3></div><button onClick={() => showToast("All teaching patterns opened")}>View all <ArrowUpRight size={14} /></button></div><div className="learned-grid"><div className="learned-card"><span>01</span><p>You frequently introduce difficult concepts through everyday analogies.</p><small>Pattern confidence · 92%</small></div><div className="learned-card"><span>02</span><p>You tend to move from simple concepts toward progressively harder applications.</p><small>Pattern confidence · 88%</small></div><div className="learned-card"><span>03</span><p>Your feedback usually explains the mistake before revealing the answer.</p><small>Pattern confidence · 81%</small></div></div></div></>;
}
